Minor fix, updated maintainers, and changed homepage location to redhat-developer
LightGuard/blinkr pull request #6
Opened 2017-10-04 09:30 UTC by RubyGemTSL

2017-10-04 19:51 UTC, RubyGemTSL commented
@LightGuard could you please merge? I don't have the correct privileges. Added myself as a maintainer, and changed homepage location to redhat-developer/blinkr. Also includes a small fix to a bug in blinkr as it was chomping index.html of links that needed it causing false failures. This has been fixed for a month or so (we're still pointing broken link checks to my fork).

I'm beginning to start preparing this code for a release to rubygems. I just need to make a few tweaks, and also update the README file.

2017-10-04 20:31 UTC, LightGuard requested changes

2017-10-04 20:31 UTC, LightGuard commented on .gitignore
> +.idea/.rakeTasks
I think simply ignoring `.idea` should be enough

2017-10-04 20:31 UTC, LightGuard commented on blinkr.gemspec
> +  spec.authors = ['Ian Hamilton', 'Jason Porter']
Pete was still the original author, he should still be listed.

2017-10-05 07:06 UTC, ianrhamilton commented
@LightGuard thanks for the review. Pushed changed to address your comments.

2017-10-11 15:10 UTC, RubyGemTSL commented
@LightGuard is there anymore changes I need to make to this?

2017-10-11 16:54 UTC, merged